#!/usr/bin/env python3

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure_analysis

f = [
    get_filter(num_lines=284,
               abs_tolerance=1.0e-10)
]

# invoke the command line interface parser which returns options
options = cli()

ierr=0
ierr += run(options,
            configure_analysis,
            input_files=['analysis_pqr_bem.tar.gz -w pqr -n 1 -freq 1.91'],
            filters={'/analysis_pqr_bem-Ex-1.9100000000-Im.pqr':f})

sys.exit(ierr)
