#!/usr/bin/env python3

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure_analysis

f = [
    get_filter(num_lines=1000,
               abs_tolerance=1.0e-10)
]

# invoke the command line interface parser which returns options
options = cli()

ierr=0
ierr += run(options,
            configure_analysis,
            input_files=['analysis_field_3d_y_bem.tar.gz -w field -n 1 -freq 1.91 -field_dir y -nx_points 30 -ny_points 30 -nz_points 30'],
            filters={'/analysis_field_3d_y_bem-Ey-1.9100000000.cube':f})

sys.exit(ierr)
