#!/usr/bin/env python3

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure

f = [
    get_filter(from_string=' I am cleaning',
               to_string='Maxima Analysis',
               rel_tolerance=1.0e-3)
]

# invoke the command line interface parser which returns options
options = cli()

ierr=0
ierr += run(options,
            configure,
            input_files=['wfq_sodium_geom_sphere.yaml'],
            filters={'log':f})

sys.exit(ierr)
