#!/usr/bin/env python3

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure_analysis

f = [
    get_filter(num_lines=1000,
               abs_tolerance=1.0e-10)
]

# invoke the command line interface parser which returns options
options = cli()

ierr=0
ierr += run(options,
            configure_analysis,
            input_files=['analysis_density_2d_x_wfq_sodium.tar.gz -w density -n 1 -freq 1.58 -field_dir x -plane xy -n_plane 1 -start 6.35 -nx_points 100 -ny_points 100'],
            filters={'/planes/xy/analysis_density_2d_x_wfq_sodium-Ex-1.5800000000-p-6.35-densityIm.csv':f, 
                     '/planes/xy/analysis_density_2d_x_wfq_sodium-Ex-1.5800000000-p-6.35-densityIm.py':f,
                     '/planes/xy/analysis_density_2d_x_wfq_sodium-Ex-1.5800000000-p-6.35-densityRe.csv':f, 
                     '/planes/xy/analysis_density_2d_x_wfq_sodium-Ex-1.5800000000-p-6.35-densityRe.py':f})

sys.exit(ierr)
