#!/usr/bin/env python3

import os
import sys
import shutil
import glob
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure_analysis


script_dir = os.path.dirname(os.path.abspath(__file__))
for d in glob.glob(os.path.join(script_dir, 'post_process*')):
    if os.path.isdir(d):
        shutil.rmtree(d)


f = [
    get_filter(from_string="Calculation of effective volume",
               num_lines=5,
               abs_tolerance=1.0e-10)
]

# invoke the command line interface parser which returns options
options = cli()

ierr=0
ierr += run(options,
            configure_analysis,
            input_files=['analysis_field_volume_z_wfqfmu_au.tar.gz -w field -n 1 -freq 3.00 -field_dir z -nx_points 30 -ny_points 30 -nz_points 30 -volume -min_grid 10.0,-4.0,-4.0 -max_grid 12.0,4.0,4.0'],
            filters={'/analysis_field_volume_z_wfqfmu_au_analysis.log':f})

sys.exit(ierr)
