macro(add_plasmonX_runtest _name _labels)
    add_test(
        ${_name}
        python3 ${PROJECT_BINARY_DIR}/tests/${_name}/test --binary-dir=${PROJECT_BINARY_DIR}  --work-dir=${PROJECT_BINARY_DIR}/tests/${_name} --verbose)
    if(NOT "${_labels}" STREQUAL "")
        set_tests_properties(${_name} PROPERTIES LABELS "${_labels}")
    endif()
endmacro()

# All tests here should contain the label "plasmonX"

# Add a keyword for the length of the test: 
# 
# 	short < 30 seconds
# 	medium > 30 seconds < 120 seconds
# 	long > 120 seconds < 200 seconds
# 	verylong > 200 seconds
# 
# NEVER comment out tests
add_plasmonX_runtest(fq_energy                                            "plasmonX;fq;energy")
add_plasmonX_runtest(fq_principal_axis_energy                             "plasmonX;fq;energy;prnaxes")
add_plasmonX_runtest(fq_polarizability                                    "plasmonX;fq;static;polar")
add_plasmonX_runtest(fqfmu_energy                                         "plasmonX;fqfmu;energy")
add_plasmonX_runtest(fqfmu_rq_rmu_energy                                  "plasmonX;fqfmu;rqrmu;energy")
add_plasmonX_runtest(wfq_sodium_inversion                                 "plasmonX;wfq;sodium;na;inversion;np")
add_plasmonX_runtest(wfq_sodium_minimal_input                             "plasmonX;wfq;sodium;na;inversion;np;minimal")
add_plasmonX_runtest(wfq_sodium_restart                                   "plasmonX;wfq;sodium;na;inversion;np;minimal;restart")
add_plasmonX_runtest(wfq_sodium_geom_sphere                               "plasmonX;wfq;sodium;na;inversion;np;minimal;geom;sphere")
add_plasmonX_runtest(wfq_sodium_geom_rod                                  "plasmonX;wfq;sodium;na;inversion;np;minimal;geom;rod")
add_plasmonX_runtest(wfqfmu_ag_inversion                                  "plasmonX;wfqfmu;inversion;silver;ag;minimal")
add_plasmonX_runtest(wfqfmu_ag_internal_permittivity                      "plasmonX;wfqfmu;inversion;silver;ag;minimal;epsilon")
add_plasmonX_runtest(wfqfmu_ag_minimal_input                              "plasmonX;wfqfmu;inversion;silver;ag;minimal")
add_plasmonX_runtest(wfqfmu_au_minimal_input                              "plasmonX;wfqfmu;inversion;gold;au;minimal")
add_plasmonX_runtest(wfqfmu_ag_read_xyz                                   "plasmonX;wfqfmu;inversion;silver;ag;minimal;xyz")
add_plasmonX_runtest(wfqfmu_au_read_xyz                                   "plasmonX;wfqfmu;inversion;gold;au;minimal;xyz")
add_plasmonX_runtest(wfqfmu_ag_diff_units                                 "plasmonX;wfqfmu;inversion;silver;ag;units")
add_plasmonX_runtest(wfqfmu_ag_restart                                    "plasmonX;wfqfmu;inversion;silver;ag;restart")
add_plasmonX_runtest(wfqfmu_ag_geom_sphere                                "plasmonX;wfqfmu;inversion;silver;ag;sphere;minimal;geom")
add_plasmonX_runtest(wfqfmu_ag_geom_sphere_units                          "plasmonX;wfqfmu;inversion;silver;ag;sphere;minimal;geom;units")
add_plasmonX_runtest(wfqfmu_ag_geom_decahedron                            "plasmonX;wfqfmu;inversion;silver;ag;deca;minimal;geom")
add_plasmonX_runtest(wfqfmu_ag_geom_rod_x                                 "plasmonX;wfqfmu;inversion;silver;ag;rod;minimal;geom")
add_plasmonX_runtest(wfqfmu_ag_geom_dimer_bowtie                          "plasmonX;wfqfmu;inversion;silver;ag;dimer;bowtie;minimal;geom")
add_plasmonX_runtest(wfqfmu_au_geom_icosahedron                           "plasmonX;wfqfmu;inversion;gold;au;ico;minimal;geom")
add_plasmonX_runtest(wfqfmu_au_geom_cuboctahedron                         "plasmonX;wfqfmu;inversion;gold;au;cto;minimal;geom")
add_plasmonX_runtest(wfqfmu_au_geom_paraboloid                            "plasmonX;wfqfmu;inversion;gold;au;tip;minimal;geom")
add_plasmonX_runtest(wfqfmu_au_geom_dimer_z                               "plasmonX;wfqfmu;inversion;gold;au;dimer;minimal;geom")
add_plasmonX_runtest(wfq_graphene_disk_inversion                          "plasmonX;wfq;inversion;graphene;disk")
add_plasmonX_runtest(wfq_graphene_ribbon_inversion                        "plasmonX;wfq;inversion;graphene;ribbon")
add_plasmonX_runtest(wfq_graphene_triangle_inversion                      "plasmonX;wfq;inversion;graphene;triangle")
add_plasmonX_runtest(wfq_graphene_minimal_input                           "plasmonX;wfq;inversion;graphene;disk;minimal")
add_plasmonX_runtest(wfq_graphene_geom_disk                               "plasmonX;wfq;inversion;graphene;disk;minimal;geom")
add_plasmonX_runtest(wfq_graphene_geom_ribbon_main_armchair               "plasmonX;wfq;inversion;graphene;ribbon;armchair;ac;minimal;geom")
add_plasmonX_runtest(wfq_graphene_geom_ribbon_main_zigzag                 "plasmonX;wfq;inversion;graphene;ribbon;zigzag;zz;minimal;geom")
add_plasmonX_runtest(wfq_graphene_geom_ring                               "plasmonX;wfq;inversion;graphene;ring;minimal;geom")
add_plasmonX_runtest(wfq_graphene_geom_triangle_armchair                  "plasmonX;wfq;inversion;graphene;triangle;armchair;ac;minimal;geom")
add_plasmonX_runtest(wfq_graphene_geom_triangle_zigzag                    "plasmonX;wfq;inversion;graphene;triangle;zigzag;zz;minimal;geom")
add_plasmonX_runtest(wfqfmu_hetero_agau_inversion                         "plasmonX;wfqfmu;hetero;inversion")
add_plasmonX_runtest(wfqfmu_hetero_agau_read_1param_inversion             "plasmonX;wfqfmu;hetero;inversion")
add_plasmonX_runtest(wfqfmu_hetero_agau_default_int_param_inversion       "plasmonX;wfqfmu;hetero;inversion")
add_plasmonX_runtest(wfqfmu_hetero_agau_minimal_input                     "plasmonX;wfqfmu;hetero;inversion;minimal")
add_plasmonX_runtest(wfqfmu_hetero_agau_read_xyz                          "plasmonX;wfqfmu;hetero;inversion;minimal;xyz")
add_plasmonX_runtest(wfqfmu_hetero_agau_geom_sphere_core_shell            "plasmonX;wfqfmu;hetero;inversion;minimal;sphere;geom")
add_plasmonX_runtest(wfqfmu_hetero_agau_geom_rod_core_shell               "plasmonX;wfqfmu;hetero;inversion;minimal;rod;geom")
add_plasmonX_runtest(bem_dpcm_exact_inversion                             "plasmonX;bem;exact;inversion;dpcm;ag")
add_plasmonX_runtest(bem_ief_exact_inversion                              "plasmonX;bem;exact;inversion;ief;iefpcm;ag")
add_plasmonX_runtest(bem_ief_approximate_inversion                        "plasmonX;bem;approximate;inversion;ief;iefpcm;ag")
add_plasmonX_runtest(bem_dpcm_geom_rod                                    "plasmonX;bem;approximate;inversion;minimal;geom;rod;dpcm;ag")
add_plasmonX_runtest(bem_dpcm_geom_sphere                                 "plasmonX;bem;approximate;inversion;minimal;geom;sphere;dpcm;ag")
add_plasmonX_runtest(bem_dpcm_brendel_bormann_ag                          "plasmonX;bem;exact;inversion;brendel-bormann;bb;ag;silver;sphere;dpcm")
add_plasmonX_runtest(bem_dpcm_brendel_bormann_au                          "plasmonX;bem;exact;inversion;brendel-bormann;bb;au;gold;sphere;dpcm")
add_plasmonX_runtest(bem_dpcm_palik_ag                                    "plasmonX;bem;exact;inversion;palik;ag;silver;sphere;dpcm")
add_plasmonX_runtest(bem_dpcm_palik_au                                    "plasmonX;bem;exact;inversion;palik;au;gold;sphere;dpcm")
add_plasmonX_runtest(bem_dpcm_external_brendel_bormann_ag                 "plasmonX;bem;exact;inversion;brendel-bormann;bb;ag;silver;sphere;dpcm;external")
add_plasmonX_runtest(wfq_sodium_iterative_on_memory                       "plasmonX;wfq;sodium;na;iterative;gmres")
add_plasmonX_runtest(wfqfmu_ag_iterative_on_memory                        "plasmonX;wfqfmu;silver;ag;iterative;gmres")
add_plasmonX_runtest(wfqfmu_hetero_agau_iterative_on_memory               "plasmonX;wfqfmu;hetero;iterative;gmres")
add_plasmonX_runtest(bem_dpcm_exact_iterative_on_memory                   "plasmonX;bem;exact;iterative;gmres;dpcm")
add_plasmonX_runtest(wfq_sodium_iterative_on_the_fly                      "plasmonX;wfq;sodium;na;iterative;gmres;otf")
add_plasmonX_runtest(wfqfmu_ag_iterative_on_the_fly                       "plasmonX;wfqfmu;silver;ag;iterative;gmres;otf")
add_plasmonX_runtest(wfqfmu_hetero_agau_iterative_on_the_fly              "plasmonX;wfqfmu;iterative;gmres;otf;hetero")
add_plasmonX_runtest(analysis_xyz                                         "plasmonX_analysis;xyz")
add_plasmonX_runtest(analysis_xyz_bem                                     "plasmonX_analysis;xyz;bem")
add_plasmonX_runtest(analysis_pqr_wfq_sodium                              "plasmonX_analysis;pqr;sodium;wfq")
add_plasmonX_runtest(analysis_pqr_bem                                     "plasmonX_analysis;pqr;bem")
add_plasmonX_runtest(analysis_field_3d_x_wfq_sodium                       "plasmonX_analysis;field;3d;x;sodium;wfq;cube")
add_plasmonX_runtest(analysis_field_3d_x_wfq_sodium_plt                   "plasmonX_analysis;field;3d;x;sodium;wfq;plt")
add_plasmonX_runtest(analysis_field_3d_x_y_z_wfqfmu_ag                    "plasmonX_analysis;field;3d;z;silver;ag;wfqfmu;cube")
add_plasmonX_runtest(analysis_field_3d_x_y_z_wfqfmu_ag_plt                "plasmonX_analysis;field;3d;z;silver;ag;wfqfmu;plt")
add_plasmonX_runtest(analysis_field_3d_y_bem                              "plasmonX_analysis;field;3d;y;bem;cube")
add_plasmonX_runtest(analysis_density_3d_x_wfq_sodium                     "plasmonX_analysis;density;3d;x;sodium;wfq;cube")
add_plasmonX_runtest(analysis_density_3d_x_wfq_sodium_plt                 "plasmonX_analysis;density;3d;x;sodium;wfq;plt")
add_plasmonX_runtest(analysis_density_3d_y_wfqfmu_au                      "plasmonX_analysis;density;3d;y;gold;au;wfqfmu;cube")
add_plasmonX_runtest(analysis_density_3d_y_wfqfmu_au_plt                  "plasmonX_analysis;density;3d;y;gold;au;wfqfmu;plt")
add_plasmonX_runtest(analysis_density_2d_x_wfq_sodium                     "plasmonX_analysis;density;2d;x;xy;sodium;wfq;csv;py")
add_plasmonX_runtest(analysis_density_2d_x_wfq_sodium_n_planes            "plasmonX_analysis;density;2d;x;xy;sodium;wfq;csv;py;planes")
add_plasmonX_runtest(analysis_density_2d_y_xy_wfqfmu_ag                   "plasmonX_analysis;density;2d;y;xy;silver;wfqfmu;csv;py")
add_plasmonX_runtest(analysis_field_2d_x_yz_wfq_sodium                    "plasmonX_analysis;field;2d;x;yz;sodium;wfq;csv;py")
add_plasmonX_runtest(analysis_field_2d_z_xz_wfqfmu_ag                     "plasmonX_analysis;field;2d;z;xz;silver;ag;wfqfmu;csv;py")
add_plasmonX_runtest(analysis_field_2d_z_xz_wfqfmu_ag_reduced             "plasmonX_analysis;field;2d;reduced;z;xz;silver;ag;wfqfmu;csv;py")
add_plasmonX_runtest(analysis_field_2d_y_xy_bem                           "plasmonX_analysis;field;2d;y;xy;bem;csv;py")
add_plasmonX_runtest(analysis_field_volume_x_wfq_sodium                   "plasmonX_analysis;field;3d;x;sodium;wfq;volume;area")
add_plasmonX_runtest(analysis_field_volume_z_wfqfmu_au                    "plasmonX_analysis;field;3d;z;gold;au;wfqfmu;volume;area")

