#!/usr/bin/env python3

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure_analysis

f = [
    get_filter(num_lines=1000,
               abs_tolerance=1.0e-10)
]

# invoke the command line interface parser which returns options
options = cli()

ierr=0
ierr += run(options,
            configure_analysis,
            input_files=['analysis_field_3d_x_y_z_wfqfmu_ag.tar.gz -w field -n 1 -freq 3.0 -nx_points 30 -ny_points 30 -nz_points 30'],
            filters={'/analysis_field_3d_x_y_z_wfqfmu_ag-Ez-3.0000000000.cube':f})

sys.exit(ierr)
